package io.quarkiverse.authorization.server.token;

import java.io.Serial;

import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * A JSON Web Token generated by the authorization server.
 */
public final class Jwt extends AbstractOAuth2Token implements ClaimAccessor {

    @Serial
    private static final long serialVersionUID = 515494092048558585L;

    private final Map<String, Object> headers;
    private final Map<String, Object> claims;

    public Jwt(String tokenValue, Instant issuedAt, Instant expiresAt,
            Map<String, Object> headers, Map<String, Object> claims) {
        super(tokenValue, issuedAt, expiresAt);
        this.headers = Collections.unmodifiableMap(new LinkedHashMap<>(headers));
        this.claims = Collections.unmodifiableMap(new LinkedHashMap<>(claims));
    }

    public Map<String, Object> getHeaders() {
        return this.headers;
    }

    @Override
    public Map<String, Object> getClaims() {
        return this.claims;
    }
}
